-- MySQL Script generated by MySQL Workbench
-- Thu Nov 16 21:10:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sportNow
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sportNow` ;

-- -----------------------------------------------------
-- Schema sportNow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportNow` DEFAULT CHARACTER SET utf8 ;
USE `sportNow` ;

-- -----------------------------------------------------
-- Table `sportNow`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportNow`.`status` ;

CREATE TABLE IF NOT EXISTS `sportNow`.`status` (
  `id_status` INT(3) NOT NULL AUTO_INCREMENT,
  `status_desc` VARCHAR(20) NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportNow`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportNow`.`users` ;

CREATE TABLE IF NOT EXISTS `sportNow`.`users` (
  `id_user` INT(6) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(6) NULL,
  `user_name` VARCHAR(100) NULL,
  `user_fn` VARCHAR(50) NULL,
  `user_ln` VARCHAR(50) NULL,
  `user_email` VARCHAR(100) NULL,
  `user_birthday` DATE NULL,
  `user_password` VARCHAR(32) NULL,
  `id_user_firebase` VARCHAR(64) NULL,
  `id_status` INT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_id_status_users_idx` (`id_status` ASC) ,
  CONSTRAINT `fk_id_status_users`
    FOREIGN KEY (`id_status`)
    REFERENCES `sportNow`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportNow`.`events_activityTP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportNow`.`events_activityTP` ;

CREATE TABLE IF NOT EXISTS `sportNow`.`events_activityTP` (
  `id_events_activityTP` INT(3) NOT NULL AUTO_INCREMENT,
  `eventsTP_name` VARCHAR(5) NULL,
  `id_status` INT(3) NULL,
  PRIMARY KEY (`id_events_activityTP`),
  INDEX `fk_id_status_events_activityTP_idx` (`id_status` ASC) ,
  CONSTRAINT `fk_id_status_events_activityTP`
    FOREIGN KEY (`id_status`)
    REFERENCES `sportNow`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportNow`.`eventsTP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportNow`.`eventsTP` ;

CREATE TABLE IF NOT EXISTS `sportNow`.`eventsTP` (
  `id_eventsTP` INT(3) NOT NULL AUTO_INCREMENT,
  `eventsTP_name` VARCHAR(5) NULL,
  `id_status` INT(2) NULL,
  PRIMARY KEY (`id_eventsTP`),
  INDEX `fk_id_status_eventsTP_idx` (`id_status` ASC) ,
  CONSTRAINT `fk_id_status_eventsTP`
    FOREIGN KEY (`id_status`)
    REFERENCES `sportNow`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportNow`.`localLocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportNow`.`localLocation` ;

CREATE TABLE IF NOT EXISTS `sportNow`.`localLocation` (
  `id_localLocation` INT(2) NOT NULL AUTO_INCREMENT,
  `loc_localNumber` VARCHAR(3) NULL,
  `loc_localName` VARCHAR(40) NULL,
  `id_status` INT(3) NULL DEFAULT 1,
  PRIMARY KEY (`id_localLocation`),
  INDEX `fk_id_status_localLocation_idx` (`id_status` ASC) ,
  CONSTRAINT `fk_id_status_localLocation`
    FOREIGN KEY (`id_status`)
    REFERENCES `sportNow`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportNow`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportNow`.`events` ;

CREATE TABLE IF NOT EXISTS `sportNow`.`events` (
  `id_events` INT(10) NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(10) NULL,
  `event_startD` DATETIME NULL,
  `event_finishedD` DATETIME NULL,
  `id_localLocation` INT(2) NULL,
  `event_address` VARCHAR(200) NULL,
  `event_desc` VARCHAR(200) NULL,
  `event_sponsors` VARCHAR(200) NULL,
  `id_eventsTP` INT(3) NULL,
  `id_events_activityTP` INT(3) NULL,
  `event_currentP` INT(3) NULL,
  `event_maxP` INT(3) NULL,
  `id_user` INT(6) NULL,
  `id_status` INT(3) NULL,
  PRIMARY KEY (`id_events`),
  INDEX `fk_id_user_events_idx` (`id_user` ASC) ,
  INDEX `fk_id_status_events_idx` (`id_status` ASC) ,
  INDEX `fk_id_events_activityTP_idx` (`id_events_activityTP` ASC) ,
  INDEX `fk_id_eventsTP_idx` (`id_eventsTP` ASC) ,
  INDEX `fk_id_localLocation_events_idx` (`id_localLocation` ASC) ,
  CONSTRAINT `fk_id_user_events`
    FOREIGN KEY (`id_user`)
    REFERENCES `sportNow`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_status_events`
    FOREIGN KEY (`id_status`)
    REFERENCES `sportNow`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_events_activityTP`
    FOREIGN KEY (`id_events_activityTP`)
    REFERENCES `sportNow`.`events_activityTP` (`id_events_activityTP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_eventsTP`
    FOREIGN KEY (`id_eventsTP`)
    REFERENCES `sportNow`.`eventsTP` (`id_eventsTP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_localLocation_events`
    FOREIGN KEY (`id_localLocation`)
    REFERENCES `sportNow`.`localLocation` (`id_localLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportNow`.`forums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportNow`.`forums` ;

CREATE TABLE IF NOT EXISTS `sportNow`.`forums` (
  `id_forum` INT(10) NOT NULL AUTO_INCREMENT,
  `forum_id` VARCHAR(10) NULL,
  `id_user` INT(6) NULL,
  `id_events` INT(10) NULL,
  `id_status` INT(3) NULL,
  PRIMARY KEY (`id_forum`),
  INDEX `fk_id_events_forum_idx` (`id_events` ASC) ,
  INDEX `fk_id_users_forums_idx` (`id_user` ASC) ,
  INDEX `fk_id_status_forums_idx` (`id_status` ASC) ,
  CONSTRAINT `fk_id_events_forum`
    FOREIGN KEY (`id_events`)
    REFERENCES `sportNow`.`events` (`id_events`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_users_forums`
    FOREIGN KEY (`id_user`)
    REFERENCES `sportNow`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_status_forums`
    FOREIGN KEY (`id_status`)
    REFERENCES `sportNow`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportNow`.`msgs_forums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportNow`.`msgs_forums` ;

CREATE TABLE IF NOT EXISTS `sportNow`.`msgs_forums` (
  `id_msg_forum` INT NOT NULL AUTO_INCREMENT,
  `msg_forum` VARCHAR(200) NULL,
  `id_user` INT(6) NULL,
  `id_forum` INT(10) NULL,
  `id_status` INT(3) NULL,
  PRIMARY KEY (`id_msg_forum`),
  INDEX `fk_id_forum_msgs_idx` (`id_forum` ASC) ,
  INDEX `fk_id_status_msgs_idx` (`id_status` ASC) ,
  CONSTRAINT `fk_id_forum_msgs`
    FOREIGN KEY (`id_forum`)
    REFERENCES `sportNow`.`forums` (`id_forum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_status_msgs`
    FOREIGN KEY (`id_status`)
    REFERENCES `sportNow`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO status VALUES (1, 'Activo');

INSERT INTO localLocation (loc_localNumber, loc_localName) VALUES
  ('001', 'Acajete'),
	('002', 'Acatlán'),
	('003', 'Acayucan'),
	('004', 'Actopan'),
	('005', 'Acula'),
	('006', 'Acultzingo'),
	('007', 'Camarón de Tejeda'),
	('008', 'Alpatláhuac'),
	('009', 'Alto Lucero de Gutiérrez Barrios'),
	('010', 'Altotonga'),
	('011', 'Alvarado'),
	('012', 'Amatitlán'),
	('013', 'Naranjos Amatlán'),
	('014', 'Amatlán de los Reyes'),
	('015', 'Angel R. Cabada'),
	('016', 'La Antigua'),
	('017', 'Apazapan'),
	('018', 'Aquila'),
	('019', 'Astacinga'),
	('020', 'Atlahuilco'),
	('021', 'Atoyac'),
	('022', 'Atzacan'),
	('023', 'Atzalan'),
	('024', 'Tlaltetela'),
	('025', 'Ayahualulco'),
	('026', 'Banderilla'),
	('027', 'Benito Juárez'),
	('028', 'Boca del Río'),
	('029', 'Calcahualco'),
	('030', 'Camerino Z. Mendoza'),
	('031', 'Carrillo Puerto'),
	('032', 'Catemaco'),
	('033', 'Cazones de Herrera'),
	('034', 'Cerro Azul'),
	('035', 'Citlaltépetl'),
	('036', 'Coacoatzintla'),
	('037', 'Coahuitlán'),
	('038', 'Coatepec'),
	('039', 'Coatzacoalcos'),
	('040', 'Coatzintla'),
	('041', 'Coetzala'),
	('042', 'Colipa'),
	('043', 'Comapa'),
	('044', 'Córdoba'),
	('045', 'Cosamaloapan de Carpio'),
	('046', 'Cosautlán de Carvajal'),
	('047', 'Coscomatepec'),
	('048', 'Cosoleacaque'),
	('049', 'Cotaxtla'),
	('050', 'Coxquihui'),
	('051', 'Coyutla'),
	('052', 'Cuichapa'),
	('053', 'Cuitláhuac'),
	('054', 'Chacaltianguis'),
	('055', 'Chalma'),
	('056', 'Chiconamel'),
	('057', 'Chiconquiaco'),
	('058', 'Chicontepec'),
	('059', 'Chinameca'),
	('060', 'Chinampa de Gorostiza'),
	('061', 'Las Choapas'),
	('062', 'Chocamán'),
	('063', 'Chontla'),
	('064', 'Chumatlán'),
	('065', 'Emiliano Zapata'),
	('066', 'Espinal'),
	('067', 'Filomeno Mata'),
	('068', 'Fortín'),
	('069', 'Gutiérrez Zamora'),
	('070', 'Hidalgotitlán'),
	('071', 'Huatusco'),
	('072', 'Huayacocotla'),
	('073', 'Hueyapan de Ocampo'),
	('074', 'Huiloapan de Cuauhtémoc'),
	('075', 'Ignacio de la Llave'),
	('076', 'Ilamatlán'),
	('077', 'Isla'),
	('078', 'Ixcatepec'),
	('079', 'Ixhuacán de los Reyes'),
	('080', 'Ixhuatlán del Café'),
	('081', 'Ixhuatlancillo'),
	('082', 'Ixhuatlán del Sureste'),
	('083', 'Ixhuatlán de Madero'),
	('084', 'Ixmatlahuacan'),
	('085', 'Ixtaczoquitlán'),
	('086', 'Jalacingo'),
	('087', 'Xalapa'),
	('088', 'Jalcomulco'),
	('089', 'Jáltipan'),
	('090', 'Jamapa'),
	('091', 'Jesús Carranza'),
	('092', 'Xico'),
	('093', 'Jilotepec'),
	('094', 'Juan Rodríguez Clara'),
	('095', 'Juchique de Ferrer'),
	('096', 'Landero y Coss'),
	('097', 'Lerdo de Tejada'),
	('098', 'Magdalena'),
	('099', 'Maltrata'),
	('100', 'Manlio Fabio Altamirano'),
	('101', 'Mariano Escobedo'),
	('102', 'Martínez de la Torre'),
	('103', 'Mecatlán'),
	('104', 'Mecayapan'),
	('105', 'Medellín de Bravo'),
	('106', 'Miahuatlán'),
	('107', 'Las Minas'),
	('108', 'Minatitlán'),
	('109', 'Misantla'),
	('110', 'Mixtla de Altamirano'),
	('111', 'Moloacán'),
	('112', 'Naolinco'),
	('113', 'Naranjal'),
	('114', 'Nautla'),
	('115', 'Nogales'),
	('116', 'Oluta'),
	('117', 'Omealca'),
	('118', 'Orizaba'),
	('119', 'Otatitlán'),
	('120', 'Oteapan'),
	('121', 'Ozuluama de Mascareñas'),
	('122', 'Pajapan'),
	('123', 'Pánuco'),
	('124', 'Papantla'),
	('125', 'Paso del Macho'),
	('126', 'Paso de Ovejas'),
	('127', 'La Perla'),
	('128', 'Perote'),
	('129', 'Platón Sánchez'),
	('130', 'Playa Vicente'),
	('131', 'Poza Rica de Hidalgo'),
	('132', 'Las Vigas de Ramírez'),
	('133', 'Pueblo Viejo'),
	('134', 'Puente Nacional'),
	('135', 'Rafael Delgado'),
	('136', 'Rafael Lucio'),
	('137', 'Los Reyes'),
	('138', 'Río Blanco'),
	('139', 'Saltabarranca'),
	('140', 'San Andrés Tenejapan'),
	('141', 'San Andrés Tuxtla'),
	('142', 'San Juan Evangelista'),
	('143', 'Santiago Tuxtla'),
	('144', 'Sayula de Alemán'),
	('145', 'Soconusco'),
	('146', 'Sochiapa'),
	('147', 'Soledad Atzompa'),
	('148', 'Soledad de Doblado'),
	('149', 'Soteapan'),
	('150', 'Tamalín'),
	('151', 'Tamiahua'),
	('152', 'Tampico Alto'),
	('153', 'Tancoco'),
	('154', 'Tantima'),
	('155', 'Tantoyuca'),
	('156', 'Tatatila'),
	('157', 'Castillo de Teayo'),
	('158', 'Tecolutla'),
	('159', 'Tehuipango'),
	('160', 'Álamo Temapache'),
	('161', 'Tempoal'),
	('162', 'Tenampa'),
	('163', 'Tenochtitlán'),
	('164', 'Teocelo'),
	('165', 'Tepatlaxco'),
	('166', 'Tepetlán'),
	('167', 'Tepetzintla'),
	('168', 'Tequila'),
	('169', 'José Azueta'),
	('170', 'Texcatepec'),
	('171', 'Texhuacán'),
	('172', 'Texistepec'),
	('173', 'Tezonapa'),
	('174', 'Tierra Blanca'),
	('175', 'Tihuatlán'),
	('176', 'Tlacojalpan'),
	('177', 'Tlacolulan'),
	('178', 'Tlacotalpan'),
	('179', 'Tlacotepec de Mejía'),
	('180', 'Tlachichilco'),
	('181', 'Tlalixcoyan'),
	('182', 'Tlalnelhuayocan'),
	('183', 'Tlapacoyan'),
	('184', 'Tlaquilpa'),
	('185', 'Tlilapan'),
	('186', 'Tomatlán'),
	('187', 'Tonayán'),
	('188', 'Totutla'),
	('189', 'Tuxpan'),
	('190', 'Tuxtilla'),
	('191', 'Ursulo Galván'),
	('192', 'Vega de Alatorre'),
	('193', 'Veracruz'),
	('194', 'Villa Aldama'),
	('195', 'Xoxocotla'),
	('196', 'Yanga'),
	('197', 'Yecuatla'),
	('198', 'Zacualpan'),
	('199', 'Zaragoza'),
	('200', 'Zentla'),
	('201', 'Zongolica'),
	('202', 'Zontecomatlán de López y Fuentes'),
	('203', 'Zozocolco de Hidalgo'),
	('204', 'Agua Dulce'),
	('205', 'El Higo'),
	('206', 'Nanchital de Lázaro Cárdenas del Río'),
	('207', 'Tres Valles'),
	('208', 'Carlos A. Carrillo'),
	('209', 'Tatahuicapan de Juárez'),
	('210', 'Uxpanapa'),
	('211', 'San Rafael'),
	('212', 'Santiago Sochiapan');
